spring:
  application:
    name: user-provider
  datasource:
    url : jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8
    username : root
    password : 123
    driverClassName : org.mariadb.jdbc.Driver
    max-active : 20
    max-idle : 8
    min-idle : 8
    initial-size : 10
    hikari:
          max-lifetime: 1765000
          maximum-pool-size: 10
mybatis:
  type-aliases-package: com.ralap.user.domain
  configuration.map-underscore-to-camel-case: true

logging:
  level:
    com.ralap.user.mapper: debug

eureka:
  client:
    serviceUrl:
      defaultZone: http://ralap:hjx969190@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8081
management.security.enabled: false